---
name: Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version (falls back to the next version available)'
        required: false
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: "Get latest GitHub Release"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          view_top: 1
      - name: Increase version
        id: increase_version
        run: |
          CUR_V=${{ steps.last_release.outputs.tag_name }}
          LAST_VERSION="${CUR_V/v}"
          echo "Latest version -> $LAST_VERSION"
          NEXT_VERSION=$(echo $LAST_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo ::set-output name=version::$NEXT_VERSION
      - name: Next GitHub version
        run: echo "Version increased -> ${{ steps.increase_version.outputs.version }}"
      - name: Set version
        id: set_version
        run: |
          if [ "${{ github.event.inputs.versionName }}" == "" ]; then
            echo ::set-output name=version::${{ steps.increase_version.outputs.version }}
          else
            echo ::set-output name=version::${{ github.event.inputs.versionName }}
          fi
      - name: Bump version
        run: |
          # make file runnable, might not be necessary
          chmod +x "bin/bump-version.sh"
          bin/bump-version.sh ${{ steps.set_version.outputs.version }}
      - name: Retrieve current version from package.json
        # id must be specified to retrieve the output of the step
        id: version_step
        uses: michmich112/extract-version@main
        with:
          version-file: "package.json"
          schema: major.minor.build
      - name: Validate version
        run: echo "Next release version will be -> ${{ steps.version_step.outputs.version }}"
      - name: Create release branch
        run: git checkout -b release/v${{ steps.version_step.outputs.version }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver
      - name: Composer install
        run: composer install --no-dev && composer dump-autoload
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Commit build
        id: make-commit
        run: |
          git add vendor/. --force
          git add .
          git commit -m "Adding /vendor directory to release" --no-verify
          git add assets/. --force
          git add .
          git diff-index --quiet HEAD || git commit -m 'Adding /assets directory with compiled and minified files to release' --no-verify
      - name: Push new branch
        run: git push origin release/v${{ steps.version_step.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version_step.outputs.version }}
          release_name: ${{ steps.version_step.outputs.version }}
          body: "Release of version ${{ steps.version_step.outputs.version }}. See readme.txt for details."
          draft: false
          prerelease: false
          commitish: release/v${{ steps.version_step.outputs.version }}
      - name: Remove branch
        run: git checkout master && git branch -D release/v${{ steps.version_step.outputs.version }} && git push origin --delete release/v${{ steps.version_step.outputs.version }}
    env:
      NODE_VERSION: "12.x"
      APP_VERSION: "1.0.O"