name: Get version test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        # id must be specified to retrieve the output of the step
        id: version-step
        uses: michmich112/extract-version@main
        with:
          version-file: "{'path':'./package.json', 'line':4}"
          schema: major.minor.build
      - name: test
        run: |
          echo "version -> $VERSION"
        env:
          VERSION: ${{ steps.version-step.outputs.version }}